M48
; DRILL file {KiCad 7.0.7} date 2024 April 17, Wednesday 16:31:02
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-17T16:31:02-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.1469Y-3.6981
T2
X3.656Y-2.1652
X3.656Y-3.74
X6.906Y-2.1652
X6.906Y-3.74
T0
M30
